{{ config(materialized='table') }}

CREATE OR REPLACE TABLE {{ source('staging', 'STG_DELIVERY') }} AS 
select 
    RW.ID,
    CAST(RW.DELIVERY_PERSON_AGE AS INT) AS DELIVERY_PERSON_AGE,
    RW.DELIVERY_LOCATION_LATITUDE,
    RW.DELIVERY_LOCATION_LONGITUDE,
    RW.WEATHER_CONDITIONS,
    RW.ROAD_TRAFFIC_DENSITY,
    CAST(RW.VEHICLE_CONDITION AS INT) AS VEHICLE_CONDITION,
    RW.TYPE_OF_VEHICLE,
    RW.MULTIPLE_DELIVERIES,
    RW.FESTIVAL,
    RW.DELIVERY_TARGET_TIME,
    RW.IS_DELIVERY_SUCCESSFUL,
    CAST(DP.DELIVERY_PERSON_ID AS STRING) AS DELIVERY_PERSON_ID, 
    CAST(DPR.DELIVERY_PERSON_RATINGS AS INT) AS DELIVERY_PERSON_RATINGS,
    CAST(DTT.TIME_TAKEN_MIN AS INT) AS TIME_TAKEN_MIN
from {{ source('my_raw_sources', 'RAW_DELIVERY') }} AS RW 
JOIN {{ source('my_dim_sources', 'DIM_DELIVERY_PERSON') }} AS DP
ON RW.ID = DP.ID
JOIN {{ source('my_dim_sources', 'DIM_DELIVERY_PERSON_RATING') }} AS DPR
ON DP.DELIVERY_PERSON_ID = DPR.DELIVERY_PERSON_ID
JOIN {{ source('my_dim_sources', 'DIM_DELIVERY_TIME_TAKEN') }} AS DTT
ON RW.ID = DTT.ID
WHERE IS_DELIVERY_SUCCESSFUL = 1